title: http://www.cnc6.cn
author: Lynsen Choi
logo: /assets/img/logo.png
description: CNXY Github By Lynsen Choi
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

gem "github-pages", group: :jekyll_plugins
