title: CNXY/CNC
author: Lynsen Choi
logo: /assets/img/logo.png
description: CNXY/CNC's Github By Lynsen Choi
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

gem "github-pages", group: :jekyll_plugins
